### ISSUE TITLE
Using CSS properties for repetitive styles

### ISSUE THREAD

**Issue by zannain** [cmerdian/prj-rev-bwfs-dasmoto#3]
Since the `<b>` tag formats text to be bold, there is no need to add the [`font-weight: bold` ](https://github.com/cmerdian/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts%20and%20Crafts/resources/css/style.css#L37-L40) style here. Additionally, for other areas, I noticed you used `font-weight: bold` several times. An alternative to repeating this style is to use CSS properties which will allow you to update several areas with the same style at once, as opposed to finding every instance of where a style is applied and updating it one by one. 

**[Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)**

```css
:root {
    --default-font-weight: bold;
}

#paint {
     font-weight: var(--default-font-weight);
}
```

You can also create a style-specific class

```css
.bold {
   font-weight: bold;
 }
```
Now you can give multiple element tags a class attribute of `bold` and they will all receive this common style. This is in fact how CSS libraries such as [Bootstrap](https://getbootstrap.com/) work.
